config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/about'
  # Defines the root path route ("/")
  root 'home#index'
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was added successfully." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :address, :birthday, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.first_name%>
    <%= contact.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= contact.address %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= contact.birthday %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <a href="//www.twitter.com/<%= contact.twitter %>" target="_blank" class="twitter">
    <%= contact.twitter %>
    </a>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container form">
    <div class="form-row">
      <%= form.label :first_name, style: "display: block" %>
      <%= form.text_field :first_name, {class: "input-group-text form-field"} %>
    </div>

    <div class="form-row">
      <%= form.label :last_name, style: "display: block" %>
      <%= form.text_field :last_name, {class: "input-group-text form-field"} %>
    </div>

    <div class="form-row">
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email, {class: "input-group-text form-field"} %>
    </div>

    <div class="form-row">
      <%= form.label :phone, style: "display: block" %>
      <%= form.text_field :phone, {class: "input-group-text form-field"} %>
    </div>

    <div class="form-row">
      <%= form.label :address, style: "display: block" %>
      <%= form.text_area :address, {class: "input-group-text form-field"} %>
    </div>

    <div class="form-row">
      <%= form.label :birthday, style: "display: block" %>
      <%= form.date_field :birthday, {class: "input-group-text form-field"} %>
    </div>

    <div class="form-row">
      <%= form.label :twitter, style: "display: block" %>
      <%= form.text_field :twitter , {class: "input-group-text form-field"} %>
    </div>

    <div class="formSubmit">
    <%= form.submit class:"formSubmit"%>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>
<h2>All Contacts</h2>
<div id="contacts" class="container">
  <% @contacts.each do |contact| %>
    <div class="card contact">
        <div class="card-body">
          <%= render contact %>
        </div>
        <button type="button" class="btn btn-info show-contact">
          <%= link_to "VIEW", contact %>
        </button>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

app/views/contacts/show.html.erb
<div class="container-sm">
<p style="color: green"><%= notice %></p>
<div class="card contact-view">
  <div class="card-body">
    <%= render @contact %>

    <div>
      <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
      <%= link_to "Delete this contact", @contact, method: :delete %>
    </div>
  </div>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Address Book', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

        </li>
        <li class="nav-item">
        <%= link_to 'Contacts', contacts_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Add Contact', new_contact_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Find a contact" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'About', home_about_path, class:"nav-link about" %>

        </li>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About the page...</h1>

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>This is the home page!</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Address Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
      <div class="container">
    <br>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>